parameters:
    ezpublish.fieldType.owenhancedrelationlist.class: 'OpenWide\Publish\EnhancedRelationListBundle\FieldType\OwEnhancedRelationList\Type'
    ezpublish.fieldType.owenhancedrelationlist.converter.class: 'OpenWide\Publish\EnhancedRelationListBundle\Persistence\Legacy\Content\FieldValue\Converter\OwEnhancedRelationList'
#twig extension
    owenhancedrelationlist.twig.extension.class: 'OpenWide\Publish\EnhancedRelationListBundle\Twig\OwEnhancedRelationListExtension'
#helpers
    owenhancedrelationlist.common_helper.class: 'OpenWide\Publish\EnhancedRelationListBundle\Helper\CommonHelper'

services:
    ezpublish.fieldType.owenhancedrelationlist:
        class: %ezpublish.fieldType.owenhancedrelationlist.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: owenhancedrelationlist}

    ezpublish.fieldType.owenhancedrelationlist.converter:
        class: %ezpublish.fieldType.owenhancedrelationlist.converter.class%
        arguments: [@ezpublish.api.storage_engine.legacy.dbhandler, @service_container]
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: owenhancedrelationlist}

#twig extension
    owenhancedrelationlist.twig.extension:
        class: %owenhancedrelationlist.twig.extension.class%
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

#helpers
    owenhancedrelationlist.common_helper:
        class: %owenhancedrelationlist.common_helper.class%
        arguments: [@ezpublish.api.repository]
        calls:
            - [ setContainer,[ @service_container ] ]