parameters:
    ezpublish.fieldType.owenhancedrelationlist.class: 'Ow\Bundle\OwEnhancedRelationListBundle\FieldType\OwEnhancedRelationList\Type'
    ezpublish.fieldType.owenhancedrelationlist.converter.class: 'Ow\Bundle\OwEnhancedRelationListBundle\Persistence\Legacy\Content\FieldValue\Converter\OwEnhancedRelationList'

services:
    ezpublish.fieldType.owenhancedrelationlist:
        class: %ezpublish.fieldType.owenhancedrelationlist.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: owenhancedrelationlist}

    ezpublish.fieldType.owenhancedrelationlist.converter:
        class: %ezpublish.fieldType.owenhancedrelationlist.converter.class%
        arguments: [@ezpublish.api.storage_engine.legacy.dbhandler, @service_container]
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: owenhancedrelationlist}